name: Revert development environment

on:
  workflow_dispatch:


jobs:
  revert_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/ && touch ./deploy.key
          echo "$SSH_PRIVATE_KEY" > ./deploy.key
          sudo chmod 600 ./deploy.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash

        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}


      - name: Install PM2
        run: npm i -g pm2

      - name: Revert PM2 deploy
        run: pm2 deploy ecosystem.config.js dev revert 1

